# Generated by Django 4.1.2 on 2022-11-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PersonID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(help_text='Enter your first name', max_length=200)),
                ('MiddleName', models.CharField(help_text='Enter your middle name', max_length=200)),
                ('LastName', models.CharField(help_text='Enter your last name', max_length=200)),
                ('HighestDegree', models.CharField(help_text='Enter your highest degree obtained', max_length=200)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('WebsiteLink', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('YearOfPassing', models.IntegerField()),
                ('Resume', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('UniversityID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('WebsiteLink', models.CharField(blank=True, max_length=200, null=True)),
                ('DomainName', models.CharField(max_length=200)),
                ('DiscussionLink', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'University',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Role', models.CharField(max_length=200)),
                ('Password', models.CharField(help_text='Enter your Password', max_length=200)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Email', models.CharField(help_text='Enter your University email', max_length=200)),
            ],
            options={
                'db_table': 'UserEmail',
            },
        ),
        migrations.CreateModel(
            name='StudentProfessor',
            fields=[
                ('StudProfID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Followers', models.IntegerField()),
                ('UniversityID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.university')),
            ],
            options={
                'db_table': 'StudentProfessor',
            },
        ),
    ]
